name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
    - run: ndk-build
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: |
          ${{ github.workspace }}/obj/local/arm64-v8a/libtcore.so
          ${{ github.workspace }}/obj/local/arm64-v8a/libtestso.so
          ${{ github.workspace }}/obj/local/arm64-v8a/tinjector
